"""add telemetry table

Revision ID: 45951ab5184e
Revises: 463911d6fe36
Create Date: 2026-09-08 01:08:11.892233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45951ab5184e'
down_revision: Union[str, Sequence[str], None] = '463911d6fe36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solar_system_id', sa.Integer(), nullable=False),
    sa.Column('pv_voltage', sa.Float(), nullable=True),
    sa.Column('pv_current', sa.Float(), nullable=True),
    sa.Column('pv_power', sa.Float(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('battery_current', sa.Float(), nullable=True),
    sa.Column('battery_soc', sa.Float(), nullable=True),
    sa.Column('load_power', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['solar_system_id'], ['solar_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_solar_system_id'), ['solar_system_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_solar_system_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_created_at'))

    op.drop_table('telemetry')
    # ### end Alembic commands ###
