"""add telemetry fault fields

Revision ID: 7f2cea3e10ef
Revises: 45951ab5184e
Create Date: 2026-09-08 06:21:16.746390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2cea3e10ef'
down_revision: Union[str, Sequence[str], None] = '45951ab5184e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fault_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fault_severity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_column('fault_severity')
        batch_op.drop_column('fault_type')

    # ### end Alembic commands ###
