"""create devices table

Revision ID: 8c1a412bdebc
Revises: b80a934a78c8
Create Date: 2026-09-26 15:05:53.236621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1a412bdebc'
down_revision: Union[str, Sequence[str], None] = 'b80a934a78c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solar_system_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=150), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['solar_system_id'], ['solar_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_api_key_hash'), ['api_key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_solar_system_id'), ['solar_system_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_solar_system_id'))
        batch_op.drop_index(batch_op.f('ix_devices_serial_number'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))
        batch_op.drop_index(batch_op.f('ix_devices_api_key_hash'))

    op.drop_table('devices')
    # ### end Alembic commands ###
